apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
      app: {{ .Release.Name }}-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
  selector:
     app: {{ .Release.Name }}

